### ISSUE TITLE
Make it work in IE

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/spyfallx#2]
I tried out the game, it it's pretty slick :)

I came up with a few suggestions, and I will open them as individual issues... Feel free to close them immediately! :joy: 

-----

Low priority for me. I was just trying to get 3 players, and noticed it didn't work in IE... The `Create New Game` and `Join Game` buttons don't do anything when clicked. (Not even a console error.) And the buttons' text is black instead of white.

![capture2](https://user-images.githubusercontent.com/1833684/44126712-5d48d866-9fff-11e8-844d-a0afbb665c76.PNG)

**Comment by ArtskydJ** [comment]
Whoops, I see you have a todo.md file... Would you rather have these #2, #3, #4, #5 listed in todo.md?

**Comment by TehShrike** [comment]
Issues are fine for now, the screenshots are nice.

What version of IE?  I'm explicitly only targeting modern browsers, so it should work in Edge 16+, but not anything older.

https://caniuse.com/#feat=es6-module

**Comment by ArtskydJ** [comment]
IE 11

**Comment by TehShrike** [comment]
Cool - I'm not supporting that version.

You should check out the client-side source code, it's pretty glorious!
