### ISSUE TITLE
Make it clear that a user's name is expected

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/spyfallx#3]
Make it clear that a user's name is expected. Maybe it is already clear enough. But with the `Create New Game` button below the text input box, I thought maybe I was making a name for the game? Maybe I just get confused easily, haha.

**Comment by TehShrike** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/1141869/44158522-7d185100-a07a-11e8-9c10-76943542921b.png">

This seems like an issue with the labeling of the input... it does say "Your name", but maybe it's not clear enough that label is associated with the input.

Maybe moving them a bit closer to each other would help?

**Comment by TehShrike** [comment]
I moved the labels 4px closer to the inputs, what do you think?

<img width="354" alt="image" src="https://user-images.githubusercontent.com/1141869/44178583-a061f100-a0b8-11e8-903c-178add07d38f.png">

**Comment by ArtskydJ** [comment]
The input/label distance wasn't throwing me off.

I just thought maybe I was supposed to come up with a name for the game I was creating, or the name for the game I was joining...

I'm comfortable closing this issue.

**Comment by TehShrike** [comment]
I updated the placeholder text to hopefully be more indicative of what should be typed into the fields:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1141869/44237312-a669d780-a175-11e8-884e-4e180e0af65e.png">
