### ISSUE TITLE
Make it so you can "check off" people or locations

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/spyfallx#4]
https://spyfall.crabhat.com/ has this feature, and I really like it. Basically, you tap/click a person if you think they are not the spy. (If you're the spy, you tap/click a location if you rule it out.) Click the player/location again to un-cross them out.

Example:
![capture](https://user-images.githubusercontent.com/1833684/44126248-b2ad170c-9ffc-11e8-94b3-c4a219008bc9.PNG)

**Comment by TehShrike** [comment]
Yeah, this should be on the "nice to have" list.

**Comment by TehShrike** [comment]
If you, or anyone else, want to take a stab at this, it can be implemented entirely inside of the [game view component](https://github.com/TehShrike/spyfallx/blob/master/client/GameState.html) (Svelte).

The first version doesn't need to save the toggle states of all the people/locations anywhere, it can just keep them in the component's state.
