### ISSUE TITLE
Tapping Start Game without enough players doesn't do anything

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/spyfallx#5]
When I tap `Start Game` with one or two users in the room, I don't get feedback as to why it fails.

I would expect some visual indication that three or more players are expected. Maybe the button should be grayed out? Maybe in the place where players show up there could be a message?

For example:
![capture3](https://user-images.githubusercontent.com/1833684/44126872-3c92309e-a000-11e8-9f33-5834a700b855.PNG)

**Comment by ArtskydJ** [comment]
I see this is in todo.md

**Comment by TehShrike** [comment]
hmm, maybe that "Waiting for game to start" message should read "Waiting for {n} more players"
